#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda___Hall_Omnisports
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Agenda_-_Hall_Omnisports")]
	public partial class DATABASEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertSALLE(SALLE instance);
    partial void UpdateSALLE(SALLE instance);
    partial void DeleteSALLE(SALLE instance);
    partial void InsertUTILISATEUR(UTILISATEUR instance);
    partial void UpdateUTILISATEUR(UTILISATEUR instance);
    partial void DeleteUTILISATEUR(UTILISATEUR instance);
    partial void InsertRESERVATION(RESERVATION instance);
    partial void UpdateRESERVATION(RESERVATION instance);
    partial void DeleteRESERVATION(RESERVATION instance);
    #endregion
		
		public DATABASEDataContext() : 
				base(global::Agenda___Hall_Omnisports.Properties.Settings.Default.Agenda___Hall_OmnisportsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATABASEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SALLE> SALLE
		{
			get
			{
				return this.GetTable<SALLE>();
			}
		}
		
		public System.Data.Linq.Table<UTILISATEUR> UTILISATEUR
		{
			get
			{
				return this.GetTable<UTILISATEUR>();
			}
		}
		
		public System.Data.Linq.Table<RESERVATION> RESERVATION
		{
			get
			{
				return this.GetTable<RESERVATION>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateSalle")]
		public int UpdateSalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> capacite, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> surface, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string detail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nom, capacite, surface, detail);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Registration")]
		public int Registration([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pseudo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string activite, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string numTel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string web)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo, password, nom, prenom, activite, numTel, email, web);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateReservation")]
		public int UpdateReservation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string detail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> heureDebut, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> heureFin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> minDebut, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> minFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nom, date, detail, heureDebut, heureFin, minDebut, minFin);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modification")]
		public int Modification([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pseudo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string activite, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string numTel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string web)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo, password, nom, prenom, activite, numTel, email, web);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUser")]
		public ISingleResult<GetUserResult> GetUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pseudo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo);
			return ((ISingleResult<GetUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSalleById")]
		public ISingleResult<GetSalleByIdResult> GetSalleById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetSalleByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSalle")]
		public ISingleResult<GetSalleResult> GetSalle()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetSalleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetIdUtilisateur")]
		public ISingleResult<GetIdUtilisateurResult> GetIdUtilisateur([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pseudo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo);
			return ((ISingleResult<GetIdUtilisateurResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllSalleName")]
		public ISingleResult<GetAllSalleNameResult> GetAllSalleName()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllSalleNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteSalle")]
		public int DeleteSalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteReservation")]
		public int DeleteReservation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Connexion")]
		public int Connexion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pseudo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllReservation")]
		public ISingleResult<GetAllReservationResult> GetAllReservation()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllReservationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetReservation")]
		public ISingleResult<GetReservationResult> GetReservation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pseudo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pseudo);
			return ((ISingleResult<GetReservationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllUserName")]
		public ISingleResult<GetAllUserNameResult> GetAllUserName()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllUserNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllReservationByDateAndSalle")]
		public ISingleResult<GetAllReservationByDateAndSalleResult> GetAllReservationByDateAndSalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nomSalle)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date, nomSalle);
			return ((ISingleResult<GetAllReservationByDateAndSalleResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALLE")]
	public partial class SALLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Salle;
		
		private string _Nom;
		
		private int _Capacite;
		
		private int _Surface;
		
		private string _Detail;
		
		private EntitySet<RESERVATION> _RESERVATION;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SalleChanging(int value);
    partial void OnID_SalleChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnCapaciteChanging(int value);
    partial void OnCapaciteChanged();
    partial void OnSurfaceChanging(int value);
    partial void OnSurfaceChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    #endregion
		
		public SALLE()
		{
			this._RESERVATION = new EntitySet<RESERVATION>(new Action<RESERVATION>(this.attach_RESERVATION), new Action<RESERVATION>(this.detach_RESERVATION));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Salle
		{
			get
			{
				return this._ID_Salle;
			}
			set
			{
				if ((this._ID_Salle != value))
				{
					this.OnID_SalleChanging(value);
					this.SendPropertyChanging();
					this._ID_Salle = value;
					this.SendPropertyChanged("ID_Salle");
					this.OnID_SalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacite", DbType="Int NOT NULL")]
		public int Capacite
		{
			get
			{
				return this._Capacite;
			}
			set
			{
				if ((this._Capacite != value))
				{
					this.OnCapaciteChanging(value);
					this.SendPropertyChanging();
					this._Capacite = value;
					this.SendPropertyChanged("Capacite");
					this.OnCapaciteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surface", DbType="Int NOT NULL")]
		public int Surface
		{
			get
			{
				return this._Surface;
			}
			set
			{
				if ((this._Surface != value))
				{
					this.OnSurfaceChanging(value);
					this.SendPropertyChanging();
					this._Surface = value;
					this.SendPropertyChanged("Surface");
					this.OnSurfaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALLE_RESERVATION", Storage="_RESERVATION", ThisKey="ID_Salle", OtherKey="ID_Salle")]
		public EntitySet<RESERVATION> RESERVATION
		{
			get
			{
				return this._RESERVATION;
			}
			set
			{
				this._RESERVATION.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RESERVATION(RESERVATION entity)
		{
			this.SendPropertyChanging();
			entity.SALLE = this;
		}
		
		private void detach_RESERVATION(RESERVATION entity)
		{
			this.SendPropertyChanging();
			entity.SALLE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UTILISATEUR")]
	public partial class UTILISATEUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Utilisateur;
		
		private string _Pseudo;
		
		private string _Password;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Activite;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _Web;
		
		private EntitySet<RESERVATION> _RESERVATION;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UtilisateurChanging(int value);
    partial void OnID_UtilisateurChanged();
    partial void OnPseudoChanging(string value);
    partial void OnPseudoChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnActiviteChanging(string value);
    partial void OnActiviteChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebChanging(string value);
    partial void OnWebChanged();
    #endregion
		
		public UTILISATEUR()
		{
			this._RESERVATION = new EntitySet<RESERVATION>(new Action<RESERVATION>(this.attach_RESERVATION), new Action<RESERVATION>(this.detach_RESERVATION));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Utilisateur
		{
			get
			{
				return this._ID_Utilisateur;
			}
			set
			{
				if ((this._ID_Utilisateur != value))
				{
					this.OnID_UtilisateurChanging(value);
					this.SendPropertyChanging();
					this._ID_Utilisateur = value;
					this.SendPropertyChanged("ID_Utilisateur");
					this.OnID_UtilisateurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pseudo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pseudo
		{
			get
			{
				return this._Pseudo;
			}
			set
			{
				if ((this._Pseudo != value))
				{
					this.OnPseudoChanging(value);
					this.SendPropertyChanging();
					this._Pseudo = value;
					this.SendPropertyChanged("Pseudo");
					this.OnPseudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activite", DbType="NVarChar(50)")]
		public string Activite
		{
			get
			{
				return this._Activite;
			}
			set
			{
				if ((this._Activite != value))
				{
					this.OnActiviteChanging(value);
					this.SendPropertyChanging();
					this._Activite = value;
					this.SendPropertyChanged("Activite");
					this.OnActiviteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="NVarChar(50)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this.OnWebChanging(value);
					this.SendPropertyChanging();
					this._Web = value;
					this.SendPropertyChanged("Web");
					this.OnWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTILISATEUR_RESERVATION", Storage="_RESERVATION", ThisKey="ID_Utilisateur", OtherKey="ID_Utilisateur")]
		public EntitySet<RESERVATION> RESERVATION
		{
			get
			{
				return this._RESERVATION;
			}
			set
			{
				this._RESERVATION.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RESERVATION(RESERVATION entity)
		{
			this.SendPropertyChanging();
			entity.UTILISATEUR = this;
		}
		
		private void detach_RESERVATION(RESERVATION entity)
		{
			this.SendPropertyChanging();
			entity.UTILISATEUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RESERVATION")]
	public partial class RESERVATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Reservation;
		
		private string _NomR;
		
		private System.DateTime _Date;
		
		private string _Detail;
		
		private int _ID_Utilisateur;
		
		private int _ID_Salle;
		
		private int _HeureDebut;
		
		private int _HeureFin;
		
		private int _MinDebut;
		
		private int _MinFin;
		
		private EntityRef<SALLE> _SALLE;
		
		private EntityRef<UTILISATEUR> _UTILISATEUR;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ReservationChanging(int value);
    partial void OnID_ReservationChanged();
    partial void OnNomRChanging(string value);
    partial void OnNomRChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    partial void OnID_UtilisateurChanging(int value);
    partial void OnID_UtilisateurChanged();
    partial void OnID_SalleChanging(int value);
    partial void OnID_SalleChanged();
    partial void OnHeureDebutChanging(int value);
    partial void OnHeureDebutChanged();
    partial void OnHeureFinChanging(int value);
    partial void OnHeureFinChanged();
    partial void OnMinDebutChanging(int value);
    partial void OnMinDebutChanged();
    partial void OnMinFinChanging(int value);
    partial void OnMinFinChanged();
    #endregion
		
		public RESERVATION()
		{
			this._SALLE = default(EntityRef<SALLE>);
			this._UTILISATEUR = default(EntityRef<UTILISATEUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Reservation", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Reservation
		{
			get
			{
				return this._ID_Reservation;
			}
			set
			{
				if ((this._ID_Reservation != value))
				{
					this.OnID_ReservationChanging(value);
					this.SendPropertyChanging();
					this._ID_Reservation = value;
					this.SendPropertyChanged("ID_Reservation");
					this.OnID_ReservationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomR
		{
			get
			{
				return this._NomR;
			}
			set
			{
				if ((this._NomR != value))
				{
					this.OnNomRChanging(value);
					this.SendPropertyChanging();
					this._NomR = value;
					this.SendPropertyChanged("NomR");
					this.OnNomRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur", DbType="Int NOT NULL")]
		public int ID_Utilisateur
		{
			get
			{
				return this._ID_Utilisateur;
			}
			set
			{
				if ((this._ID_Utilisateur != value))
				{
					if (this._UTILISATEUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UtilisateurChanging(value);
					this.SendPropertyChanging();
					this._ID_Utilisateur = value;
					this.SendPropertyChanged("ID_Utilisateur");
					this.OnID_UtilisateurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle", DbType="Int NOT NULL")]
		public int ID_Salle
		{
			get
			{
				return this._ID_Salle;
			}
			set
			{
				if ((this._ID_Salle != value))
				{
					if (this._SALLE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SalleChanging(value);
					this.SendPropertyChanging();
					this._ID_Salle = value;
					this.SendPropertyChanged("ID_Salle");
					this.OnID_SalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureDebut", DbType="Int NOT NULL")]
		public int HeureDebut
		{
			get
			{
				return this._HeureDebut;
			}
			set
			{
				if ((this._HeureDebut != value))
				{
					this.OnHeureDebutChanging(value);
					this.SendPropertyChanging();
					this._HeureDebut = value;
					this.SendPropertyChanged("HeureDebut");
					this.OnHeureDebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureFin", DbType="Int NOT NULL")]
		public int HeureFin
		{
			get
			{
				return this._HeureFin;
			}
			set
			{
				if ((this._HeureFin != value))
				{
					this.OnHeureFinChanging(value);
					this.SendPropertyChanging();
					this._HeureFin = value;
					this.SendPropertyChanged("HeureFin");
					this.OnHeureFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDebut", DbType="Int NOT NULL")]
		public int MinDebut
		{
			get
			{
				return this._MinDebut;
			}
			set
			{
				if ((this._MinDebut != value))
				{
					this.OnMinDebutChanging(value);
					this.SendPropertyChanging();
					this._MinDebut = value;
					this.SendPropertyChanged("MinDebut");
					this.OnMinDebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinFin", DbType="Int NOT NULL")]
		public int MinFin
		{
			get
			{
				return this._MinFin;
			}
			set
			{
				if ((this._MinFin != value))
				{
					this.OnMinFinChanging(value);
					this.SendPropertyChanging();
					this._MinFin = value;
					this.SendPropertyChanged("MinFin");
					this.OnMinFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALLE_RESERVATION", Storage="_SALLE", ThisKey="ID_Salle", OtherKey="ID_Salle", IsForeignKey=true)]
		public SALLE SALLE
		{
			get
			{
				return this._SALLE.Entity;
			}
			set
			{
				SALLE previousValue = this._SALLE.Entity;
				if (((previousValue != value) 
							|| (this._SALLE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SALLE.Entity = null;
						previousValue.RESERVATION.Remove(this);
					}
					this._SALLE.Entity = value;
					if ((value != null))
					{
						value.RESERVATION.Add(this);
						this._ID_Salle = value.ID_Salle;
					}
					else
					{
						this._ID_Salle = default(int);
					}
					this.SendPropertyChanged("SALLE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTILISATEUR_RESERVATION", Storage="_UTILISATEUR", ThisKey="ID_Utilisateur", OtherKey="ID_Utilisateur", IsForeignKey=true)]
		public UTILISATEUR UTILISATEUR
		{
			get
			{
				return this._UTILISATEUR.Entity;
			}
			set
			{
				UTILISATEUR previousValue = this._UTILISATEUR.Entity;
				if (((previousValue != value) 
							|| (this._UTILISATEUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTILISATEUR.Entity = null;
						previousValue.RESERVATION.Remove(this);
					}
					this._UTILISATEUR.Entity = value;
					if ((value != null))
					{
						value.RESERVATION.Add(this);
						this._ID_Utilisateur = value.ID_Utilisateur;
					}
					else
					{
						this._ID_Utilisateur = default(int);
					}
					this.SendPropertyChanged("UTILISATEUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetUserResult
	{
		
		private int _ID_Utilisateur;
		
		private string _Pseudo;
		
		private string _Password;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Activite;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _Web;
		
		public GetUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur", DbType="Int NOT NULL")]
		public int ID_Utilisateur
		{
			get
			{
				return this._ID_Utilisateur;
			}
			set
			{
				if ((this._ID_Utilisateur != value))
				{
					this._ID_Utilisateur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pseudo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pseudo
		{
			get
			{
				return this._Pseudo;
			}
			set
			{
				if ((this._Pseudo != value))
				{
					this._Pseudo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this._Prenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activite", DbType="NVarChar(50)")]
		public string Activite
		{
			get
			{
				return this._Activite;
			}
			set
			{
				if ((this._Activite != value))
				{
					this._Activite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="NVarChar(50)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this._Web = value;
				}
			}
		}
	}
	
	public partial class GetSalleByIdResult
	{
		
		private int _ID_Salle;
		
		private string _Nom;
		
		private int _Capacite;
		
		private int _Surface;
		
		private string _Detail;
		
		public GetSalleByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle", DbType="Int NOT NULL")]
		public int ID_Salle
		{
			get
			{
				return this._ID_Salle;
			}
			set
			{
				if ((this._ID_Salle != value))
				{
					this._ID_Salle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacite", DbType="Int NOT NULL")]
		public int Capacite
		{
			get
			{
				return this._Capacite;
			}
			set
			{
				if ((this._Capacite != value))
				{
					this._Capacite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surface", DbType="Int NOT NULL")]
		public int Surface
		{
			get
			{
				return this._Surface;
			}
			set
			{
				if ((this._Surface != value))
				{
					this._Surface = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this._Detail = value;
				}
			}
		}
	}
	
	public partial class GetSalleResult
	{
		
		private int _ID_Salle;
		
		private string _Nom;
		
		private int _Capacite;
		
		private int _Surface;
		
		private string _Detail;
		
		public GetSalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle", DbType="Int NOT NULL")]
		public int ID_Salle
		{
			get
			{
				return this._ID_Salle;
			}
			set
			{
				if ((this._ID_Salle != value))
				{
					this._ID_Salle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacite", DbType="Int NOT NULL")]
		public int Capacite
		{
			get
			{
				return this._Capacite;
			}
			set
			{
				if ((this._Capacite != value))
				{
					this._Capacite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surface", DbType="Int NOT NULL")]
		public int Surface
		{
			get
			{
				return this._Surface;
			}
			set
			{
				if ((this._Surface != value))
				{
					this._Surface = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this._Detail = value;
				}
			}
		}
	}
	
	public partial class GetIdUtilisateurResult
	{
		
		private int _ID_Utilisateur;
		
		public GetIdUtilisateurResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur", DbType="Int NOT NULL")]
		public int ID_Utilisateur
		{
			get
			{
				return this._ID_Utilisateur;
			}
			set
			{
				if ((this._ID_Utilisateur != value))
				{
					this._ID_Utilisateur = value;
				}
			}
		}
	}
	
	public partial class GetAllSalleNameResult
	{
		
		private string _nom;
		
		public GetAllSalleNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this._nom = value;
				}
			}
		}
	}
	
	public partial class GetAllReservationResult
	{
		
		private int _ID_Reservation;
		
		private string _NomR;
		
		private System.DateTime _Date;
		
		private string _Detail;
		
		private int _ID_Utilisateur;
		
		private int _ID_Salle;
		
		private int _HeureDebut;
		
		private int _HeureFin;
		
		private int _MinDebut;
		
		private int _MinFin;
		
		private int _ID_Utilisateur1;
		
		private string _Pseudo;
		
		private string _Password;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Activite;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _Web;
		
		public GetAllReservationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Reservation", DbType="Int NOT NULL")]
		public int ID_Reservation
		{
			get
			{
				return this._ID_Reservation;
			}
			set
			{
				if ((this._ID_Reservation != value))
				{
					this._ID_Reservation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomR
		{
			get
			{
				return this._NomR;
			}
			set
			{
				if ((this._NomR != value))
				{
					this._NomR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this._Detail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur", DbType="Int NOT NULL")]
		public int ID_Utilisateur
		{
			get
			{
				return this._ID_Utilisateur;
			}
			set
			{
				if ((this._ID_Utilisateur != value))
				{
					this._ID_Utilisateur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle", DbType="Int NOT NULL")]
		public int ID_Salle
		{
			get
			{
				return this._ID_Salle;
			}
			set
			{
				if ((this._ID_Salle != value))
				{
					this._ID_Salle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureDebut", DbType="Int NOT NULL")]
		public int HeureDebut
		{
			get
			{
				return this._HeureDebut;
			}
			set
			{
				if ((this._HeureDebut != value))
				{
					this._HeureDebut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureFin", DbType="Int NOT NULL")]
		public int HeureFin
		{
			get
			{
				return this._HeureFin;
			}
			set
			{
				if ((this._HeureFin != value))
				{
					this._HeureFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDebut", DbType="Int NOT NULL")]
		public int MinDebut
		{
			get
			{
				return this._MinDebut;
			}
			set
			{
				if ((this._MinDebut != value))
				{
					this._MinDebut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinFin", DbType="Int NOT NULL")]
		public int MinFin
		{
			get
			{
				return this._MinFin;
			}
			set
			{
				if ((this._MinFin != value))
				{
					this._MinFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur1", DbType="Int NOT NULL")]
		public int ID_Utilisateur1
		{
			get
			{
				return this._ID_Utilisateur1;
			}
			set
			{
				if ((this._ID_Utilisateur1 != value))
				{
					this._ID_Utilisateur1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pseudo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pseudo
		{
			get
			{
				return this._Pseudo;
			}
			set
			{
				if ((this._Pseudo != value))
				{
					this._Pseudo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this._Prenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activite", DbType="NVarChar(50)")]
		public string Activite
		{
			get
			{
				return this._Activite;
			}
			set
			{
				if ((this._Activite != value))
				{
					this._Activite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="NVarChar(50)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this._Web = value;
				}
			}
		}
	}
	
	public partial class GetReservationResult
	{
		
		private int _ID_Reservation;
		
		private string _NomR;
		
		private System.DateTime _Date;
		
		private string _Detail;
		
		private int _ID_Utilisateur;
		
		private int _ID_Salle;
		
		private int _HeureDebut;
		
		private int _HeureFin;
		
		private int _MinDebut;
		
		private int _MinFin;
		
		private int _ID_Utilisateur1;
		
		private string _Pseudo;
		
		private string _Password;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Activite;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _Web;
		
		public GetReservationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Reservation", DbType="Int NOT NULL")]
		public int ID_Reservation
		{
			get
			{
				return this._ID_Reservation;
			}
			set
			{
				if ((this._ID_Reservation != value))
				{
					this._ID_Reservation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomR
		{
			get
			{
				return this._NomR;
			}
			set
			{
				if ((this._NomR != value))
				{
					this._NomR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this._Detail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur", DbType="Int NOT NULL")]
		public int ID_Utilisateur
		{
			get
			{
				return this._ID_Utilisateur;
			}
			set
			{
				if ((this._ID_Utilisateur != value))
				{
					this._ID_Utilisateur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle", DbType="Int NOT NULL")]
		public int ID_Salle
		{
			get
			{
				return this._ID_Salle;
			}
			set
			{
				if ((this._ID_Salle != value))
				{
					this._ID_Salle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureDebut", DbType="Int NOT NULL")]
		public int HeureDebut
		{
			get
			{
				return this._HeureDebut;
			}
			set
			{
				if ((this._HeureDebut != value))
				{
					this._HeureDebut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureFin", DbType="Int NOT NULL")]
		public int HeureFin
		{
			get
			{
				return this._HeureFin;
			}
			set
			{
				if ((this._HeureFin != value))
				{
					this._HeureFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDebut", DbType="Int NOT NULL")]
		public int MinDebut
		{
			get
			{
				return this._MinDebut;
			}
			set
			{
				if ((this._MinDebut != value))
				{
					this._MinDebut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinFin", DbType="Int NOT NULL")]
		public int MinFin
		{
			get
			{
				return this._MinFin;
			}
			set
			{
				if ((this._MinFin != value))
				{
					this._MinFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur1", DbType="Int NOT NULL")]
		public int ID_Utilisateur1
		{
			get
			{
				return this._ID_Utilisateur1;
			}
			set
			{
				if ((this._ID_Utilisateur1 != value))
				{
					this._ID_Utilisateur1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pseudo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pseudo
		{
			get
			{
				return this._Pseudo;
			}
			set
			{
				if ((this._Pseudo != value))
				{
					this._Pseudo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this._Prenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activite", DbType="NVarChar(50)")]
		public string Activite
		{
			get
			{
				return this._Activite;
			}
			set
			{
				if ((this._Activite != value))
				{
					this._Activite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="NVarChar(50)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this._Web = value;
				}
			}
		}
	}
	
	public partial class GetAllUserNameResult
	{
		
		private string _Pseudo;
		
		public GetAllUserNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pseudo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pseudo
		{
			get
			{
				return this._Pseudo;
			}
			set
			{
				if ((this._Pseudo != value))
				{
					this._Pseudo = value;
				}
			}
		}
	}
	
	public partial class GetAllReservationByDateAndSalleResult
	{
		
		private int _ID_Reservation;
		
		private string _NomR;
		
		private System.DateTime _Date;
		
		private string _Detail;
		
		private int _ID_Utilisateur;
		
		private int _ID_Salle;
		
		private int _HeureDebut;
		
		private int _HeureFin;
		
		private int _MinDebut;
		
		private int _MinFin;
		
		private int _ID_Utilisateur1;
		
		private string _Pseudo;
		
		private string _Password;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _Activite;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _Web;
		
		private int _ID_Salle1;
		
		private string _Nom1;
		
		private int _Capacite;
		
		private int _Surface;
		
		private string _Detail1;
		
		public GetAllReservationByDateAndSalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Reservation", DbType="Int NOT NULL")]
		public int ID_Reservation
		{
			get
			{
				return this._ID_Reservation;
			}
			set
			{
				if ((this._ID_Reservation != value))
				{
					this._ID_Reservation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomR
		{
			get
			{
				return this._NomR;
			}
			set
			{
				if ((this._NomR != value))
				{
					this._NomR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this._Detail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur", DbType="Int NOT NULL")]
		public int ID_Utilisateur
		{
			get
			{
				return this._ID_Utilisateur;
			}
			set
			{
				if ((this._ID_Utilisateur != value))
				{
					this._ID_Utilisateur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle", DbType="Int NOT NULL")]
		public int ID_Salle
		{
			get
			{
				return this._ID_Salle;
			}
			set
			{
				if ((this._ID_Salle != value))
				{
					this._ID_Salle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureDebut", DbType="Int NOT NULL")]
		public int HeureDebut
		{
			get
			{
				return this._HeureDebut;
			}
			set
			{
				if ((this._HeureDebut != value))
				{
					this._HeureDebut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureFin", DbType="Int NOT NULL")]
		public int HeureFin
		{
			get
			{
				return this._HeureFin;
			}
			set
			{
				if ((this._HeureFin != value))
				{
					this._HeureFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDebut", DbType="Int NOT NULL")]
		public int MinDebut
		{
			get
			{
				return this._MinDebut;
			}
			set
			{
				if ((this._MinDebut != value))
				{
					this._MinDebut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinFin", DbType="Int NOT NULL")]
		public int MinFin
		{
			get
			{
				return this._MinFin;
			}
			set
			{
				if ((this._MinFin != value))
				{
					this._MinFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Utilisateur1", DbType="Int NOT NULL")]
		public int ID_Utilisateur1
		{
			get
			{
				return this._ID_Utilisateur1;
			}
			set
			{
				if ((this._ID_Utilisateur1 != value))
				{
					this._ID_Utilisateur1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pseudo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pseudo
		{
			get
			{
				return this._Pseudo;
			}
			set
			{
				if ((this._Pseudo != value))
				{
					this._Pseudo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this._Nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this._Prenom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activite", DbType="NVarChar(50)")]
		public string Activite
		{
			get
			{
				return this._Activite;
			}
			set
			{
				if ((this._Activite != value))
				{
					this._Activite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="NVarChar(50)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this._Web = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Salle1", DbType="Int NOT NULL")]
		public int ID_Salle1
		{
			get
			{
				return this._ID_Salle1;
			}
			set
			{
				if ((this._ID_Salle1 != value))
				{
					this._ID_Salle1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom1
		{
			get
			{
				return this._Nom1;
			}
			set
			{
				if ((this._Nom1 != value))
				{
					this._Nom1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacite", DbType="Int NOT NULL")]
		public int Capacite
		{
			get
			{
				return this._Capacite;
			}
			set
			{
				if ((this._Capacite != value))
				{
					this._Capacite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surface", DbType="Int NOT NULL")]
		public int Surface
		{
			get
			{
				return this._Surface;
			}
			set
			{
				if ((this._Surface != value))
				{
					this._Surface = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail1", DbType="NVarChar(MAX)")]
		public string Detail1
		{
			get
			{
				return this._Detail1;
			}
			set
			{
				if ((this._Detail1 != value))
				{
					this._Detail1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
